# Generated by Django 3.2.9 on 2021-11-29 14:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0004_auto_20211129_2105'),
    ]

    operations = [
        migrations.RenameField(
            model_name='message',
            old_name='RoomID',
            new_name='roomID',
        ),
        migrations.RenameField(
            model_name='room',
            old_name='RoomName',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='room',
            old_name='Password',
            new_name='password',
        ),
    ]
