# Generated by Django 3.2.9 on 2021-11-30 12:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0006_auto_20211129_2332'),
    ]

    operations = [
        migrations.RenameField(
            model_name='information',
            old_name='Birthday',
            new_name='birthday',
        ),
        migrations.RenameField(
            model_name='information',
            old_name='ImageLink',
            new_name='inmage_link',
        ),
        migrations.RenameField(
            model_name='information',
            old_name='Status',
            new_name='status',
        ),
    ]
