# Generated by Django 3.2.9 on 2021-11-30 12:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0007_auto_20211130_1903'),
    ]

    operations = [
        migrations.RenameField(
            model_name='message',
            old_name='roomID',
            new_name='room',
        ),
    ]
