# Generated by Django 3.2.8 on 2021-12-03 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0009_roomhistory'),
    ]

    operations = [
        migrations.AlterField(
            model_name='information',
            name='inmage_link',
            field=models.ImageField(null=True, upload_to=''),
        ),
    ]
