# Generated by Django 3.2.8 on 2021-12-03 10:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0010_alter_information_inmage_link'),
    ]

    operations = [
        migrations.RenameField(
            model_name='information',
            old_name='inmage_link',
            new_name='inmagelink',
        ),
    ]
