# Generated by Django 3.2.8 on 2021-12-03 10:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0011_rename_inmage_link_information_inmagelink'),
    ]

    operations = [
        migrations.RenameField(
            model_name='information',
            old_name='inmagelink',
            new_name='imagelink',
        ),
    ]
