# Generated by Django 3.2.8 on 2021-12-03 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0012_rename_inmagelink_information_imagelink'),
    ]

    operations = [
        migrations.AlterField(
            model_name='information',
            name='birthday',
            field=models.DateTimeField(),
        ),
    ]
