# Generated by Django 3.2.8 on 2021-12-13 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0014_auto_20211213_1124'),
    ]

    operations = [
        migrations.AlterField(
            model_name='information',
            name='imagelink',
            field=models.ImageField(blank=True, null=True, upload_to='users/'),
        ),
    ]
